### ISSUE TITLE
tesa_findpulsepeak does not work

### ISSUE THREAD

**Issue by FrancoisThiffault** [nigelrogasch/TESA#2]
Dear Nigel,
@nigelrogasch 

I received this error when I tried to use the tesa_findpulsepeak function. 

EEGLAB error in function dwgetspike() at line 49: Index exceeds the number of array elements(1).

I wanted to use tesa_findpulsepeak as an alternative to test_findpulse because the latter function cannot identify peak in numerous datasets. Ironically, the alternative, test_findpulsepeak, does work at all.

I attach to this message a dataset where I successfully identified 692 repetitive trains with 5 pulses using the function test_find pulse. I used the following parameters : Fc3 as channel, 190 ms as latency, 1000 as rate, 3600 as ITI and 5 as the number of pulses.

Please note that those data are confidential and should be used to only help me identify the problem with tesa_findpulsepeak/dwgetspike functions.

.fdt file : 
https://uqtrsspt-my.sharepoint.com/:u:/g/personal/francois_thiffault2_uqtr_ca/ESNv0F8H3tdIkWvlWsALiVMB4MNIQ7M2NvSLeJALhTZ7TA?e=ysIGCd

.set file:
https://uqtrsspt-my.sharepoint.com/:u:/g/personal/francois_thiffault2_uqtr_ca/EaMRjKOG8ixOrpbkw2CqPkgBmtirrKDpKy3B5B-FMjWV4Q?e=3F7ard

Thank a lot,
François Thiffault
PhD student
Université du Québec à Trois-Rivières

**Comment by caleycaleycaley** [comment]
Dear François, 
tesa_findpulsepeak function works on continuous files. 
Can recommend using it before epoching your data.

scripted example:
EEG = pop_loadset(['continous_tmseeg.set']);
EEG = eeg_checkset( EEG );
EEG = tesa_findpulsepeak( EEG, 'FC3', 'dtrnd', 'poly', 'thrshtype','dynamic', 'wpeaks', 'neg', 'plots', 'on', 'tmsLabel', 'X');

**Comment by FrancoisThiffault** [comment]
Dear Nigel,

Thank again for your very quick feedback !
The dataset that I used and transfer to you, except error, is a continuous file. 

I tried to use the command line instead of the gui with the line you wrote. It gave me the same error (see the print screen) attached. I use Matlab 2019b update 5 with EEGLAB 2019.1
<img width="921" alt="Capture d’écran, le 2020-03-24 à 20 30 18" src="https://user-images.githubusercontent.com/32601833/77490177-8bab1a80-6e10-11ea-950a-c99a5ad3c1cc.png">

**Comment by caleycaleycaley** [comment]
Dear François, 
I see your data is recorded with sampling rate 1000Hz, 
tesa_findpulsepeak function expected data recorded at higher sample rates. 

Its possible to fix this in future updates. 

In the meantime,  you can make the following changes to your local copy of "tesa_findpulsepeak.m"
replace: 
213 - spk = detectspike((dat),tms,thrsh,1*EEG.srate,10*EEG.srate); 
with:
213 - spk = detectspike(dat,tms,thrsh,10*EEG.srate,100*EEG.srate); 

Regards 
Caley

**Comment by FrancoisThiffault** [comment]
Dear Nigel,

The change makes the function works just fine. 

Best,
François
