### ISSUE TITLE
,Why is this a problem?How can I solve it?

### ISSUE THREAD

**Issue by xp752926566** [nigelrogasch/TESA#7]
excuse me ,Why is this a problem?How can I solve it?please look following picture:

![image](https://user-images.githubusercontent.com/45249364/118791329-31e59980-b8c9-11eb-8aae-fbfa3421659e.png)

**Comment by nigelrogasch** [comment]
Hi,
The issue is because Matlab can't recognise the 'datetime' function. This was introduced in Matlab 2014b - what version of Matlab are you using?

**Comment by xp752926566** [comment]
i am using Matlab2013b.If I use the version above 2013b, can I solve this problem?

**Comment by xp752926566** [comment]
> Hi,
> The issue is because Matlab can't recognise the 'datetime' function. This was introduced in Matlab 2014b - what version of Matlab are you using?

i am using Matlab2013b.If I use the version above 2013b, can I solve this problem?

**Comment by nigelrogasch** [comment]
TESA has only been tested for compatability with Matlab2015a onwards. But if you comment out or delete the line using the 'datetime' function (line 119 and line 123 of the code in the tesa_fastica.m function) then it should work for you.

Good luck.
