### ISSUE TITLE
pop_tesa_fastica not working

### ISSUE THREAD

**Issue by kirstinheise** [nigelrogasch/TESA#8]
Hello Nigel Rogasch, 

I am trying to run fastica within TESA (TESA v1.1.1, eeglab2021.0, Matlab R2018b on Mac OS 10.14). Despite setting the path to FastICA_25, I receive the pop_runica error "wrong value for argument 'icatype' 
when running
EEG = pop_tesa_fastica( EEG, 'approach', 'symm', 'g', 'tanh', 'stabilization', 'off');
Is it possible that there is some incompatibility of the toolboxes, Matlab etc? 

Thanks a lot for your support. 
Kirstin

**Comment by nigelrogasch** [comment]
Hi Kirstin,
I've checked the eeglab2021 inputs for the pop_runica function and can't see any obvious compatability issues. The first thing to check is whether fastica is recognisable within your matlab path. Try typing the following into the command window:
which fastica
If it is on the matlab path it should come up with the path directory. If that works, let me know and we'll try something else.
Cheers,
Nigel

**Comment by kirstinheise** [comment]
Hello Nigel, 

indeed some stupid late-night programming error prevented me from seeing that the path was not set correctly. Now, it is fastica'ing like a charm. 
Thanks for your response!!

**Comment by nigelrogasch** [comment]
Great to hear. Happy analysing!
